FROM node:20-alpine

WORKDIR /app

COPY media/package*.json ./
RUN npm ci

COPY media/ .

ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=placeholder
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID

ARG NEXT_PUBLIC_API_URL=http://localhost:8000/api
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY=placeholder
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY

ARG NEXT_PUBLIC_USE_MOCK=false
ENV NEXT_PUBLIC_USE_MOCK=$NEXT_PUBLIC_USE_MOCK

RUN npm run build

EXPOSE 3000

CMD ["npx", "next", "start"]
