export const UPLOAD_SELECTORS = {
  PAGE_HEADING: 'h1:has-text("Upload your audio files.")',
  DROPZONE:
    '[role="button"][aria-label="Drag and drop audio files or click to choose files"]',
  FILE_INPUT: 'input[type="file"]',
  TRACK_INFO_HEADING: 'text=Track Info',
  TITLE_INPUT: 'input[placeholder="Track title"]',
  ARTIST_INPUT: 'input[placeholder="Artist name"]',
  GENRE_SELECT: 'select',
  TAGS_INPUT: 'input[placeholder="Add styles, moods, tempo."]',
  DESCRIPTION_INPUT:
    'textarea[placeholder="Tracks with descriptions tend to get more plays and engagements."]',
  REPLACE_TRACK_BUTTON: 'button:has-text("Replace track")',
  CLOSE_UPLOAD_BUTTON: 'button[aria-label="Close"]',
  UPLOAD_BUTTON: 'button:has-text("Upload")',
  TITLE_REQUIRED_ERROR: 'text=Track title is required.',
  ARTWORK_INPUT: 'input[accept="image/*"]',
  ARTWORK_UPLOAD_BUTTON: 'button[aria-label="Upload artwork"]',
  ARTWORK_PREVIEW: 'img[alt="Artwork preview"]',
  ARTWORK_REMOVE_BUTTON: 'button[aria-label="Remove artwork"]',
  QUIT_CONFIRMATION_HEADING: 'text=Are you sure you want to quit?',
  BACK_TO_UPLOAD_BUTTON: 'button:has-text("Back to upload")',
  QUIT_UPLOAD_BUTTON: 'button:has-text("Quit upload")',
  SUCCESS_HEADING: 'h1:has-text("Saved to SoundCloud.")',
  SUCCESS_CTA: 'button:has-text("View track")',
  SUCCESS_TEXT: 'text=Congratulations! Your tracks are now on SoundCloud.',
  SUCCESS_CLOSE_BUTTON: 'button[aria-label="Close"]',
} as const;
